[input_mode]
hpic_mode = "pic"
simulation_tag = "rustbca_coupling"
units = "si"

[mesh]
type = "uniform"
    [mesh.type_specification]
    x1_points = [0.0, 0.01]
    x1_elem_size = 1.0e-4 # 100 elements

[time]
num_time_steps = 1000
dt = 2.0e-9

[species]
[species."e-"]
type = "boltzmann"
[species."e-".type_params]
    temperature = 116045.0

[species."H"]
mass = 1.67262192369e-27
type = "boris_buneman"
[species."H".type_params]
    atomic_number = 1
    initial_condition = "uniform_beam"
    [species."H".type_params.initial_condition_params]
        num_particles = 100000
        charge_states = [ { charge_number = 1, density = 1.0e18 } ]
        flow_velocity_1 = 0.0
        flow_velocity_2 = 0.0
        flow_velocity_3 = 0.0
        temperature = 116045.0
    [[species."H".type_params.boundary_conditions]]
        boundary = "west"
        type = "rust_bca"
        [species."H".type_params.boundary_conditions.type_params]
            incident_species_cutoff_energy = 1.60217662e-19
            incident_species_surface_binding_energy = 1.60217662e-19
            [[species."H".type_params.boundary_conditions.type_params.targets]]
                species = "B"
                wall_density = 1.309e29
                cutoff_energy = 8.01088e-19
                surface_binding_energy = 9.22854e-19
                bulk_binding_energy = 0.0
            [[species."H".type_params.boundary_conditions.type_params.targets]]
                species = "H"
                wall_density = 1.309e28
                cutoff_energy = 1.52207e-19
                surface_binding_energy = 2.40326e-19
                bulk_binding_energy = 0.0
    [[species."H".type_params.boundary_conditions]]
        boundary = "east"
        type = "rust_bca"
        [species."H".type_params.boundary_conditions.type_params]
            incident_species_cutoff_energy = 1.60217662e-19
            incident_species_surface_binding_energy = 1.60217662e-19
            [[species."H".type_params.boundary_conditions.type_params.targets]]
                species = "B"
                wall_density = 1.309e29
                cutoff_energy = 8.01088e-19
                surface_binding_energy = 9.22854e-19
                bulk_binding_energy = 0.0
            [[species."H".type_params.boundary_conditions.type_params.targets]]
                species = "H"
                wall_density = 1.309e28
                cutoff_energy = 1.52207e-19
                surface_binding_energy = 2.40326e-19
                bulk_binding_energy = 0.0
    [[species."H".type_params.volumetric_sources]]
        type = "minimum_mass"
        temperature = 116045.0

[species."B"]
mass = 1.79521e-26
type = "boris_buneman"
[species."B".type_params]
    atomic_number = 5
    initial_condition = "uniform_beam"
    [species."B".type_params.initial_condition_params]
        num_particles = 10000
        charge_states = [ { charge_number = 1, density = 1.0e12 },
                          { charge_number = 2, density = 2.0e13 },
                          { charge_number = 3, density = 4.0e13 },
                          { charge_number = 4, density = 9.0e13 },
                          { charge_number = 5, density = 2.0e13 } ]
        flow_velocity_1 = 0.0
        flow_velocity_2 = 0.0
        flow_velocity_3 = 0.0
        temperature = 116045.0
    [[species."B".type_params.boundary_conditions]]
        boundary = "west"
        type = "rust_bca"
        [species."B".type_params.boundary_conditions.type_params]
            incident_species_cutoff_energy = 8.01088e-19
            incident_species_surface_binding_energy = 9.22854e-19
            [[species."B".type_params.boundary_conditions.type_params.targets]]
                species = "B"
                wall_density = 1.309e29
                cutoff_energy = 8.01088e-19
                surface_binding_energy = 9.22854e-19
                bulk_binding_energy = 0.0
            [[species."B".type_params.boundary_conditions.type_params.targets]]
                species = "H"
                wall_density = 1.309e28
                cutoff_energy = 1.52207e-19
                surface_binding_energy = 2.40326e-19
                bulk_binding_energy = 0.0
    [[species."B".type_params.boundary_conditions]]
        boundary = "east"
        type = "rust_bca"
        [species."B".type_params.boundary_conditions.type_params]
            incident_species_cutoff_energy = 8.01088e-19
            incident_species_surface_binding_energy = 9.22854e-19
            [[species."B".type_params.boundary_conditions.type_params.targets]]
                species = "B"
                wall_density = 1.309e29
                cutoff_energy = 8.01088e-19
                surface_binding_energy = 9.22854e-19
                bulk_binding_energy = 0.0
            [[species."B".type_params.boundary_conditions.type_params.targets]]
                species = "H"
                wall_density = 1.309e28
                cutoff_energy = 1.52207e-19
                surface_binding_energy = 2.40326e-19
                bulk_binding_energy = 0.0
    [[species."B".type_params.volumetric_sources]]
        type = "minimum_mass"
        temperature = 116045.0

[interactions.electron_impact_ionization."B"]
electron_species = "e-"
A = [2.83984e-55, 2.32824e-55, 1.93601e-55, 2.04331e-55, 1.02679e-55] # [1.1063, 0.9070, 0.7542, 0.7960, 0.4000] x 10^-13 eV^2 cm^2
B = [[-2.74512e-55, -2.25637e-56], # [-1.0694, -0.0879] x 10^-13 eV^2 cm^2
        [-1.22444e-55,  5.05693e-56], # [-0.4770,  0.1970] x 10^-13 eV^2 cm^2
        [-4.85157e-57, -7.60285e-55,  1.9299e-54, -2.19299e-54,  7.98533e-55], # [-0.0189, -2.9618,  7.5182, -8.5431,  3.1108] x 10^-13 eV^2 cm^2
        [-1.28451e-55,  2.26817e-55], # [-0.5004,  0.8836] x 10^-13 eV^2 cm^2
        []]
I = [1.32981e-18, 4.0294742e-18, 6.07706e-18, 4.15557e-17, 5.45093e-17] # [8.30, 25.15, 37.93, 259.37, 340.22] eV

[interactions.electron_impact_ionization."H"]
electron_species = "e-"
A = [4.73606e-56] # 0.1845e-13 eV^2 cm^2
B = [[-4.77456e-57, 3.15994e-56, -4.87981e-56, 2.44555e-55]] # [-0.0186, 0.1231, -0.1901, 0.9527] x 10^-13 eV^2 cm^2
I = [2.17896e-18] # 13.6 eV

[magnetic_field]
type = "uniform"

[magnetic_field.type_params]
b1 = 0.0
b2 = 0.0
b3 = 0.0

[electric_potential]
poisson_solver = "tridiag"

[[electric_potential.boundary_conditions]]
boundary = "west"
type = "dirichlet"
function = "constant"
[electric_potential.boundary_conditions.function_params]
value = 0.0

[[electric_potential.boundary_conditions]]
boundary = "east"
type = "dirichlet"
function = "constant"
[electric_potential.boundary_conditions.function_params]
value = 0.0

[output_diagnostics]
    output_dir = "rustbca_coupling_example_out"

    [output_diagnostics.logging]
    log_level = "info"
    timing_log_enabled = false

    [output_diagnostics.particle_output]
    stride = 50
    source_counters = true
    species = ["B", "H"]

    [output_diagnostics.field_output]
    stride = 50
