[input_mode]
hpic_mode = "pic"
simulation_tag = "twostream"
units = "si"

[mesh]
type = "uniform"
east_west_periodic = true
    [mesh.type_specification]
    x1_points = [0.0, 0.001188]
    x1_elem_size = 2.97e-6 # 400 elements

[time]
num_time_steps = 1800
dt = 9.82e-12

[species."e-_blue"]
mass = 9.11e-31
type = "boris_buneman"
    [species."e-_blue".type_params]
    initial_condition = "uniform_beam"
        [species."e-_blue".type_params.initial_condition_params]
        num_particles = 50000
        charge_states = [ { charge_number = -1, density = 5.0e15 } ]
        flow_velocity_1 = 3.2e5
        flow_velocity_2 = 0.0
        flow_velocity_3 = 0.0

[species."e-_red"]
mass = 9.11e-31
type = "boris_buneman"
    [species."e-_red".type_params]
    initial_condition = "uniform_beam"
        [species."e-_red".type_params.initial_condition_params]
        num_particles = 50000
        charge_states = [ { charge_number = -1, density = 5.0e15 } ]
        flow_velocity_1 = -3.2e5
        flow_velocity_2 = 0.0
        flow_velocity_3 = 0.0

[species."h+"]
mass = 1.67e-27
type = "uniform_background"
    [species."h+".type_params]
    charge_number = 1
    density = 1.0e16

[magnetic_field]
type = "uniform"

[magnetic_field.type_params]
b1 = 0.0
b2 = 0.0
b3 = 0.0

[electric_potential]
poisson_solver = "hockney"

[output_diagnostics]
output_dir = "twostream_example_out"
    [output_diagnostics.logging]
    log_level = "info"
    timing_log_enabled = false
    [output_diagnostics.particle_output]
    stride = 0
    first_step = false
    final_step = true
    species = ["e-_blue", "e-_red"]
    [output_diagnostics.field_output]
    stride = 0
    first_step = false
    final_step = true
